apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-frontend
  template:
    metadata:
      labels:
        app: mern-frontend
    spec:
      containers:
        - name: mern-frontend
          image: mayansrivas/mern-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mern-frontend
spec:
  type: NodePort
  selector:
    app: mern-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
