apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-mongo
  template:
    metadata:
      labels:
        app: mern-mongo
    spec:
      containers:
        - name: mern-mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          emptyDir: {}  # For production, consider using PersistentVolumeClaim
---
apiVersion: v1
kind: Service
metadata:
  name: mern-mongo
spec:
  selector:
    app: mern-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
